I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 125, in script
    jacobs "Wait... but... What if we did an in-flight scan... and... [nerds off]"
KeyError: u'nerds off'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 125, in script
    jacobs "Wait... but... What if we did an in-flight scan... and... [nerds off]"
  File "C:\Tools\RenPy\renpy-7.2.1-sdk\renpy\ast.py", line 690, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Tools\RenPy\renpy-7.2.1-sdk\renpy\exports.py", line 1322, in say
    who(what, *args, **kwargs)
  File "C:\Tools\RenPy\renpy-7.2.1-sdk\renpy\character.py", line 1114, in __call__
    what = what_pattern.replace("[what]", sub(what, translate=True))
  File "C:\Tools\RenPy\renpy-7.2.1-sdk\renpy\character.py", line 1103, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Tools\RenPy\renpy-7.2.1-sdk\renpy\substitutions.py", line 244, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 605, in get_value
KeyError: u'nerds off'

Windows-7-6.1.7601-SP1
Ren'Py 7.2.1.457
Starseed 1.0
Sat Mar 23 18:18:58 2019
